;/* Version f1b9622831c5f758b69f8c4fafbe9659 v:4.5.0.773, c:5eb1d893d60371496c3a27129b58026291601af9, b:4.5.0.773 n:INTERNAL-BUILD */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
new function(){var g=window.ADRUM;if(g&&g.q&&!0!==window["adrum-disable"]){var z=window.console,B=z&&"function"==typeof z.log?z:{log:function(){}},v=this&&this.fh||function(){var c=Object.Xj||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return function(f,a){function b(){this.constructor=f}c(f,a);f.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}();(function(c){(function(f){f.fa=function(a){function b(c){return c.replace(/\s/g,
"")===e}var k={a:[1,2,3,"str"]},e='{"a":[1,2,3,"str"]}';if("undefined"!==typeof JSON&&JSON&&f.isFunction(JSON.stringify)&&b(JSON.stringify(k)))return JSON.stringify(a);if("undefined"!==typeof Object&&Object&&f.isFunction(Object.toJSON)&&b(Object.toJSON(k)))return Object.toJSON(a);c.error("M115");return null};f.Nb=function(a,b,k){var e=a,d=k;"xhr"===k&&(e=document.createElement("div"),a.appendChild(e),d="xhr_"+a.getElementsByTagName("div").length);a=document.createElement("p");a.innerHTML="Script loaded from "+
c.conf.adrumExtUrl+". Metrics collected are:";e.appendChild(a);a=document.createElement("table");a.id="ADRUM_"+d;var d=document.createElement("tbody"),h;for(h in b){k=document.createElement("tr");var f=document.createElement("td");f.innerHTML=h;f.className="name";var p=document.createElement("td");p.innerHTML=String(b[h]);p.className="value";k.appendChild(f);k.appendChild(p);d.appendChild(k)}a.appendChild(d);e.appendChild(a)};f.Ph=function(){function c(b,k){try{if("object"!=typeof b)return String(b);
if(0<=f.Wa(k,b))return"Already visited";k.push(b);var e;if(f.isArray(b)){for(var d="[ ",h=0;h<b.length;h++)0!=h&&(d+=", "),d+=c(b[h],k);e=d+" ]"}else{var d="{ ",h=!0,r;for(r in b)h?h=!1:d+=", ",d+=c(r,k)+" => "+c(b[r],k);e=d+" }"}return e}catch(p){return"dumpObject failed: "+p}}return function(b){return c(b,[])}}();f.Wa=f.isFunction(Array.prototype.indexOf)?function(c,b){return c.indexOf(b)}:function(c,b){for(var k=0;k<c.length;k++)if(c[k]==b)return k;return-1};f.compareWindows=function(c,b){return c==
b};f.Vb=function(c,b,k,e,d){if(!f.isDefined(b))return b;if(f.isArray(b)){c=[];for(var h=0,r=b.length;h<r;h++)c[h]=f.Vb(h,b[h],k,e,d);return c}if(f.isFunction(b))return b;if(f.isObject(b)){c={};for(h in b)f.hasOwnPropertyDefined(b,h)&&(c[k(h)]=d&&d(h)?b[h]:f.Vb(h,b[h],k,e,d));return c}return e(c,b)};f.fj=function(c){var b=[],k;for(k in c)f.hasOwnPropertyDefined(c,k)&&b.push([k,c[k]]);return b};f.gk=function(){try{localStorage.setItem("try","try");var c=localStorage.getItem("try");localStorage.removeItem("try");
return"try"===c}catch(b){return!1}};f.fk=function(){try{var c=f.fa({v:1});return 1===JSON.parse(c).v}catch(b){return!1}};f.hk=function(){return f.isFunction(window.postMessage)};f.Gh=function(c,b){var k=document.createElement("div");k.innerHTML='<iframe id="'+b+'" src='+c+' width="0" height="0" tabindex="-1" title="empty" style="display: none;"></iframe>';document.body.appendChild(k);return document.getElementById(b)};f.mf=function(c,b){f.isDefined(b)&&(c.parentPageName=b)};f.$b=function(c){return f.isNumber(c)&&
isFinite(c)&&Math.floor(c)===c};f.Jd=function(f){c.log(f);B.log(f)}})(c.utils||(c.utils={}))})(g||(g={}));(function(c){(function(c){c.tf=function(c){return/^[0-9]+$/.test(c)?Number(c):null};c.me=function(c){return"number"===typeof c&&!isNaN(c)&&isFinite(c)}})(c.utils||(c.utils={}))})(g||(g={}));(function(c){(function(f){function a(d){var e=d.split("\r\n"),k=/^\s*ADRUM_(\d+): (.+)\s*$/i;d=[];for(var b=0;b<e.length;b++){var f=e[b];try{var a=k.exec(f);a&&d.push([Number(a[1]),a[2]])}catch(g){c.exception(g,
"M118",f)}}Array.prototype.sort.call(d,function(c,d){return c[0]-d[0]});a=[];for(e=0;e<d.length;e++)a.push(d[e][1]);return a}var b=c.utils.hasOwnPropertyDefined,k=null,e=null;f.ce=function(){e||(e=f.De(f.lc(f.cookieMetadataChunks),f.lc(c.footerMetadataChunks)));return e};f.getPageGUID=function(){var d=c.monitor.DOMEventsMonitor,e=c.utils.isObject(d.currentBasePage)&&c.utils.isFunction(d.currentBasePage.guid);if(!k){var b=f.ce();k=b&&b.clientRequestGUID||(e?d.currentBasePage.guid():c.utils.generateGUID())}return k};
f.ti=function(d){d=a(d);c.log("M116",d);return f.De(f.lc(d))};f.De=function(d,e){function k(d){for(var e=0;e<d.length;e++){var h=d[e];h!=b&&0>c.utils.Wa(s,h)&&s.push(h)}}if(!d||0>=d.ja.length)return null;e||(e=d);var b;if(0<e.ja.length){if(b=e.ja[0],0>c.utils.Wa(d.ja,b))return null}else return c.error("M117"),null;var a=e.serverSnapshotType||d.serverSnapshotType,g=e.hasEntryPointErrors||d.hasEntryPointErrors,s=[];k(d.ja);k(e.ja);var q={clientRequestGUID:b,btGlobalAccountName:d.btGlobalAccountName};
0<s.length&&(q.otherClientRequestGUIDs=s);0<f.Ce(d.btTime,e.btTime).length&&(q.btTime=f.Ce(d.btTime,e.btTime));null!==a&&(q.serverSnapshotType=a);null!==g&&(q.hasEntryPointErrors=g);return q};f.Ce=function(c,e){for(var k=c.concat(e),f={},a={},g=0;g<k.length;g++){var s=k[g];s.id in f||(f[s.id]=-1);f[s.id]=Math.max(f[s.id],s.duration);s.id in a||(a[s.id]=-1);a[s.id]=Math.max(a[s.id],s.ert)}var k=[],q;for(q in f)b(f,q)&&k.push({id:q,duration:f[q],ert:a[q]});return k};f.lc=function(d){if(!c.utils.isArray(d))return null;
for(var e=[],k=null,b=[],f=null,a=null,g=0;g<d.length;g++){var q=d[g];if("string"!==typeof q)return null;q=q.replace(/^"|"$/g,"");q=decodeURIComponent(q).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===q.length){var n=q[1];switch(q[0]){case "clientRequestGUID":case "g":e.push(n);break;case "btId":case "i":b.push({id:n,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===b.length)return null;q=c.utils.tf(n);if(!c.utils.me(q)||-1>q)return null;b[b.length-1].duration=q;break;case "btERT":case "e":if(0===
b.length)return null;q=c.utils.tf(n);if(!c.utils.me(q)||-1>q)return null;b[b.length-1].ert=q;break;case "serverSnapshotType":case "s":f=n;break;case "globalAccountName":case "n":k=n;break;case "hasEntryPointErrors":case "h":a=n}}}return 0===e.length?null:{ja:e,btGlobalAccountName:k,btTime:b,serverSnapshotType:f,hasEntryPointErrors:a}};f.ul=a})(c.correlation||(c.correlation={}))})(g||(g={}));(function(c){var f=c.conf||(c.conf={});f.Lk=3E3;f.Bf=c.isDebug;f.ah=1E3;f.Ag=2;f.zg=5;f.ug=5;f.vg=20;f.dd=5E3;
f.xa=512;f.Zf=10;f.Yf=64;f.Lg=10;f.Kg=10;f.Gg=300;f.Dg=2048;f.ya=2048;f.za=760;f.we={eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",pageName:"pn",httpHeaders:"hh",parameter:"pa",navOrXhrMetrics:"mn",cookieMetrics:"mc",resourceTimingInfo:"rt",userData:"ud",userDataLong:"udl",userDataDouble:"udd",userDataBoolean:"udb",
userDataDate:"udt",errors:"er",ajaxError:"ae",xhrStatus:"xs",btTime:"bt",btGlobalAccountName:"btgan",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",BEACONS:"B",ver:"vr",eom:"em",agentId:"ai",rootGUID:"rg",events:"es",guids:"gs",urlParts:"up",sequenceId:"si",eventType:"et",eventGUID:"eg",parentType:"at",serverMetadata:"sm",eventUrl:"eu",line:"ln",message:"dm",duration:"dn",id:"id",ert:"ert",parentUrl:"au",parentPageName:"an",
geo:"ge",metrics:"mx",timestamp:"ts",country:"c",region:"r",city:"t",method:"md",clientId:"ci"}})(g||(g={}));(function(c){c=c.beacons||(c.beacons={});c.numBeaconsSent=0;c.beaconsSent=[]})(g||(g={}));(function(c){(function(f){var a=function(){function b(){}b.prototype.send=function(k,e){var d=(e?c.conf.beaconUrlHttps:c.conf.beaconUrlHttp)+c.conf.corsEndpointPath+"/"+c.conf.appKey+"/adrum",b;c.utils.isFunction(c.xhrConstructor)&&c.utils.isFunction(c.xhrOpen)?(b=new c.xhrConstructor,c.xhrOpen.call(b,
"POST",d)):(b=new XMLHttpRequest,b.open("POST",d));b.setRequestHeader("Content-type","text/plain");var a=c.utils.fa(k);null!=a&&(c.utils.isFunction(c.xhrConstructor)&&c.utils.isFunction(c.xhrSend)?c.xhrSend.call(b,a):b.send(a),c.log("M119",d),c.log("\n"),c.log("<hr/>"),c.isDebug&&f.beaconsSent.push(k),f.numBeaconsSent+=1)};return b}();f.Uf=a})(c.beacons||(c.beacons={}))})(g||(g={}));g||(g={});(function(c){var f=function(){function f(c,k,e){this.cb=c;this.Di=k;this.Ic=e}f.prototype.Tb=function(){try{return f.$d(this.Di.ADRUM)}catch(b){return c.error("M120"),
f.$d(c)}};f.$d=function(c){return c.correlation.getPageGUID()};return f}();c.Rf=f})(g||(g={}));(function(c){c.beacons||(c.beacons={})})(g||(g={}));(function(c){(function(c){var a=function(){function b(){this.Ya=[];this.Ob={}}b.prototype.ab=function(k){if(!k)return"";if(c.hasOwnPropertyDefined(this.Ob,k))return this.Ob[k];var e=this.Ya.length;this.Ob[k]=e;this.Ya[e]=k;return e};return b}();c.cd=a})(c.utils||(c.utils={}))})(g||(g={}));(function(c){(function(f){var a=c.utils.map,b=function(){function c(){}
c.bk=function(c){c=(c||"").match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]*)?(#[\s\S]*)?/);var d={};c[1]&&(d.protocol=c[1].substring(0,c[1].length-3));c[2]&&(d.path=c[2]);c[3]&&(d.Gj=c[3]);c[4]&&(d.anchor=c[4]);return d};c.Th=function(e,d){var b=c.bk(e),f="";b.protocol&&(f+=d.ab(b.protocol),f+="://");b.path&&(f+=a(b.path.split("/"),d.ab,d).join("/"));return f+=a([b.Gj,b.anchor],function(c){return c?c[0]+d.ab(c.slice(1)):""},d).join("")};c.Rh=function(c,d){return""+d.ab(c)};return c}();f.Tc=b})(c.beacons||
(c.beacons={}))})(g||(g={}));(function(c){(function(f){(function(f){function b(){var d=null,k=null;try{d=localStorage[e]}catch(b){}if(d)try{d=k=JSON.parse(d),c.utils.isObject(d)&&c.utils.isNumber(d[r])&&-1<d[r]?g=k:c.error("M121")}catch(f){c.exception(f,"M122");try{delete localStorage[e]}catch(h){c.exception(h,"M123")}}}function k(){try{var k=c.channel,b=g[d]||g[h],f=k&&k.M&&k.M.K&&k.M.K.id||(c.utils.isString(b)?b:c.utils.generateGUID());g[d]=g[h]=f;localStorage[e]=c.utils.fa(g)}catch(a){}}var e=
"ADRUM_CLIENTINFO",d="agentId",h="clientId",r="seqId",g;b();g||(g={seqId:0});k();f.ji=function(){b();var c=g[r]++;k();return c}})(f.Gd||(f.Gd={}))})(c.lf||(c.lf={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(){this.urlCapture={filterURLQuery:!1};this.Xe=/;jsessionid=[^/?]+/;f.mergeJSON(this.urlCapture,c.conf.userConf.urlCapture);f.isBoolean(this.urlCapture.filterURLQuery)||f.isArray(this.urlCapture.filterURLQuery)||(c.log("M124"),this.urlCapture.filterURLQuery=!1)}b.ak=function(c){for(var e=
0,d=0;d<c.length;d++)e=(e<<5)-e+c.charCodeAt(d),e|=0;return e};b.prototype.qi=function(c){var e="",d,b;if(!f.isString(c))return"";d=c.indexOf("?")+1;0<d&&(b=c.indexOf("#"),0>b?e=c.substring(d):d<=b&&(e=c.substring(d,b)));return e};b.prototype.Xh=function(c){var e="",d=this.urlCapture.filterURLQuery,b={},a=0,g,m,t;if(!f.isString(c)||""===c)return"";if(!1===d)return c;g=this.qi(c);if(""===g)return c;if(f.isArray(d)){for(t=0;t<d.length;t++)b[d[t]]=!0;d=g+"&";for(t=0;t<d.length;t++)switch(d[t]){case "=":m=
d.substring(a,t);break;case "&":case ";":m=m||d.substring(a,t),t++,b[m]||(e+=d.substring(a,t)),a=t,m=null}e=e.substring(0,e.length-1)}""==e&&(g="?"+g);return c.replace(g,e)};b.prototype.Z=function(c){if(null===c||void 0===c)return null;if(""===c)return"";var e=c.match(this.Xe),d=c;if(null!=e){var b=c.indexOf("?");if(0>b||b>e.index)d=c.replace(this.Xe,"")}return d=this.Xh(d)};b.prototype.Sd=function(c){if(null===c||void 0===c)return null;var e=c.indexOf("?"),d=c.indexOf("#");0>e&&(e=Number.MAX_VALUE);
0>d&&(d=Number.MAX_VALUE);return c.substring(0,Math.min(e,d))};b.prototype.qj=function(c){if(null===c||void 0===c)return null;var e=this.Sd(c);return e+"?"+b.ak(c.substring(e.length))};return b}();f.Qk=a;f.N=new a})(c.utils||(c.utils={}))})(g||(g={}));(function(c){c=c.sa||(c.sa={});c.ra||(c.ra={})})(g||(g={}));(function(c){c=c.sa||(c.sa={});c.ra||(c.ra={})})(g||(g={}));(function(c){(function(f){(function(f){var b=function(){function b(e,d,k){this.Ij=0;this.qc=[];this.fe=!1;this.xi=k;var f=this;c.utils.addEventListener(window,
"message",function(c){f.uj(c)});this.wi=c.utils.Gh(d,e)}b.prototype.uj=function(e){var d;try{if(d=JSON.parse(e.data),c.utils.isDefined(d)&&!0===d.success)if(-1===d.id&&"iframe-ready"===d.data)this.fe=!0,this.xi();else{if(this.qc[d.id])this.qc[d.id](d.data)}else c.error("M125",e.data)}catch(b){c.exception(b,"M126")}};b.prototype.send=function(e,d,b,k){if(this.fe){var f=this.Ij++;this.qc[f]=k;this.wi.contentWindow.postMessage(c.utils.fa({id:f,action:e,key:d,value:b}),"*")}};b.prototype.generateGUID=
function(c,d){this.send("generateGUID",c,null,d)};return b}();f.Wf=b})(f.ra||(f.ra={}))})(c.sa||(c.sa={}))})(g||(g={}));(function(c){(function(f){var a=function(){function e(){this.yd=new b(e.Mf);this.If=new b(e.Of);this.Dk=new k(e.Nf)}e.prototype.init=function(d){this.channel=d;c.utils.gk()&&c.utils.fk()?c.utils.hk()&&e.aj()?this.sk():this.Cf():e.Ee=!0};e.prototype.Cf=function(){var d=this.yd.load();e.Zi(d)||(d={ver:c.conf.agentVer,id:c.utils.generateGUID()},this.yd.save(d));e.K=d};e.prototype.sk=
function(){var d=this.If.load();if(e.$i(d))e.K=d;else{c.log("M127");var b=this;this.Dk.load(function(d){d&&(d={ver:c.conf.agentVer,id:d,ttl:(new Date).getTime()+e.$f},b.If.save(d),e.K=d,c.log("M128"))});b=this;c.utils.tryPeriodically(e.Db,function(){return b.isReady()},function(){b.onReady()},function(){b.gc()})}};e.aj=function(){return c.conf.userConf&&c.conf.userConf.xd&&c.conf.userConf.xd.enable};e.Zi=function(c){return c&&c.id&&0<c.id.length};e.$i=function(c){return c&&c.id&&0<c.id.length&&0===
c.id.indexOf("XD_")&&c.ttl>(new Date).getTime()};e.prototype.isReady=function(){return e.Ee||c.utils.isDefined(e.K)};e.prototype.onReady=function(){this.channel.onResolverReady()};e.prototype.gc=function(){c.log("M129");this.Cf();this.channel.onResolverReady()};e.Db=function(c){return 10<c?-1:[1,50,100,500][c-1]||1E3};return e}();a.Mf="ADRUM_AGENT_INFO";a.Of="ADRUM_XD_AGENT_INFO";a.Nf="ADRUM_XD_AGENT_ID";a.$f=6048E5;a.Ee=!1;f.M=a;var b=function(){function e(c){this.wd=c}e.prototype.load=function(){var d=
null;try{var e=localStorage.getItem(this.wd);e&&(d=JSON.parse(e))}catch(b){c.exception(b,"M130")}return d};e.prototype.save=function(d){try{var e=c.utils.fa(d);e&&localStorage.setItem(this.wd,e)}catch(b){c.exception(b,"M131")}};return e}(),k=function(){function e(c){this.mh=c}e.prototype.load=function(d){var e=this;try{var b=new c.sa.ra.Wf("cross-domain-store-server-iframe",c.conf.adrumXdUrl,function(){b.generateGUID(e.mh,d)})}catch(k){c.exception(k,"M132")}};return e}()})(c.channel||(c.channel={}))})(g||
(g={}));(function(c){(function(f){var a=c.utils.isString,b=c.utils.isNumber,k=function(){function e(){}e.prototype.hb=function(d,b,k){d={ver:c.conf.agentVer,dataType:"R",rootGUID:k.Tb(),events:d};c.channel.M.K&&c.channel.M.K.id&&(d.agentId=c.channel.M.K.id);b&&(d.geo=b);return e.Dj(d)};e.Dj=function(d){c.isDebug||(d=e.Ah(d));return d};e.Ah=function(d){var k=new c.utils.cd,g=new c.utils.cd;d=c.utils.Vb(null,d,e.Ub,function(d,m){if(!a(m))return m;if(e.Yi(d)){var t=e.Ti(d)&&b(c.conf.userConf.maxUrlLength)?
c.conf.userConf.maxUrlLength:c.conf.xa;m=e.Fc(m,t);m=f.Tc.Th(m,k)}else m=e.Si(d)?e.Fc(m,c.conf.za):e.Fc(m,c.conf.Dg);e.Mi(d)&&(m=f.Tc.Rh(m,g));return m},e.ij);d[e.Ub("guids")]=g.Ya;d[e.Ub("urlParts")]=k.Ya;return d};e.Yi=function(c){return"eventUrl"==c||"parentUrl"==c||"pageReferrer"==c||"pageUrl"==c||"u"==c};e.Mi=function(c){return"eventGUID"==c||"parentGUID"==c||"rootGUID"==c||"clientRequestGUID"==c};e.Si=function(c){return"userPageName"==c};e.Fc=function(c,e){return c.length>e?c.substr(0,e-3)+
"...":c};e.Ti=function(c){return"eventUrl"==c||"parentUrl"==c||"pageReferrer"==c};e.Ub=function(d){if(c.conf.Bf)return d;var e=c.conf.we[d];return"undefined"===typeof e?d:e};e.ij=function(c){c=""+c;return 0===c.indexOf("userData")||"parameter"===c};return e}();f.Tf=k})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(){}b.prototype.send=function(c,e){for(var d=0;d<c.length;d++)this.Tj(c[d],e)};b.prototype.Tj=function(b,e){var d=(e?c.conf.beaconUrlHttps:
c.conf.beaconUrlHttp)+c.conf.imageEndpointPath,a=document.createElement("img");try{a.src=d+b}catch(g){}c.isDebug&&f.beaconsSent.push(b);f.numBeaconsSent+=1};return b}();f.qg=a})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(c){c.Na=function(c,b){if(3>=b)return"...";c.length>b&&(c=c.substring(0,b-3)+"...");return c};c.xf=function(c,b){if(3>=b)return"...";c.length>b&&(c=c.substring(0,(b-3)/2)+"..."+c.substring(c.length-(b-3)/2,c.length));return c};c.ok=function(a,b){a.length<=b||(a=
c.Na(a,b-1),a+=":");return a};c.mk=function(a,b,k,e,d,h){a=c.ok(a,e);k=c.Na(k,d);a.length+b.length+k.length>h-3&&(b=c.Na(b,h-3-a.length-k.length));return 0<k.length?a+"//"+b+":"+k:a+"//"+b};c.nk=function(a,b,k){a=c.map(a,function(e){return c.xf(e,b)});if(a.length>k){var e=a[0];a=a.slice(a.length-k);a.unshift("...");""==e&&a.unshift(e)}return a};c.pk=function(a,b,k,e,d){e=c.mk(a.protocol,a.hostname,a.port,e,d,b);k--;d=c.Na(a.search,b);k--;var h=c.Na(a.hash,b);k--;a=a.pathname.split("/");var g="";0<
a.length&&(g=a.pop(),g=c.xf(g,b),k--);a=c.nk(a,b,k);return 0==a.length?e+g+d+h:e+a.join("/")+"/"+g+d+h}})(c.utils||(c.utils={}))})(g||(g={}));(function(c){(function(c){var a=function(){function c(){}c.Yb=function(){for(var k=0;k<c.ad.length;k++)c.V[c.ad[k]]=c.P.kg;for(k=0;k<c.Zc.length;k++)c.V[c.Zc[k]]=c.P.eg;c.V.js=c.P.Vg;c.V.css=c.P.CSS;c.V.svg=c.P.Xg;c.V.html=c.P.$c;c.V.htm=c.P.$c};c.Rb=function(c){return c.duration?c.duration:c.responseEnd&&c.startTime?c.responseEnd-c.startTime:-1};c.be=function(k){var e;
return(k=k.pathname)&&-1!=(e=k.lastIndexOf("."))?c.V[k.substring(e+1,k.length).toLowerCase()]||c.P.jd:c.P.jd};return c}();a.P={kg:"img",Vg:"script",CSS:"css",Xg:"svg",$c:"html",eg:"font",jd:"other"};a.ad="bmp gif jpeg jpg png webp".split(" ");a.Zc=["ttf","woff","otf","eot"];a.V={};c.Aa=a;a.Yb()})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){var a=function(){function c(k){function e(c){d.marks.push(0==k[c]?-1:Math.round(k[c]-d.Je))}this.marks=[];var d=this;this.Je=k.startTime;this.Ki(k)?
(this.Vd=c.Uc,e("startTime"),e("fetchStart")):(this.Vd=c.md,e("startTime"),e("redirectStart"),e("redirectEnd"),e("fetchStart"),e("domainLookupStart"),e("domainLookupEnd"),e("connectStart"),e("secureConnectionStart"),e("connectEnd"),e("requestStart"),e("responseStart"));e("responseEnd")}c.ki=function(){var k={};k[c.md]=c.Ug;k[c.Uc]=c.Vf;return k};c.prototype.Ki=function(c){return this.da(c.redirectStart)&&this.da(c.redirectEnd)&&(this.da(c.domainLookupStart)||this.da(c.domainLookupEnd)||this.da(c.connectStart)||
this.da(c.connectEnd))&&this.da(c.secureConnectionStart)};c.prototype.da=function(c){return!c||0===c};return c}();a.md=1;a.Uc=2;a.Ug="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart secureConnectionStart connectEnd requestStart responseStart responseEnd".split(" ");a.Vf=["startTime","fetchStart","responseEnd"];c.ld=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){var a=function(){function c(){}c.prototype.mb=function(c,e){if(c)return c.slice(0,
e)};return c}();c.fg=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){var a=function(){function b(){}b.prototype.mb=function(b,e){if(b){if(b.length<=e)return b;for(var d=[],a=0;a<b.length;a++)d.push({sc:b[a],index:a});d.sort(function(e,d){return-(c.Aa.Rb(e.sc)-c.Aa.Rb(d.sc))});d=d.slice(0,e);d.sort(function(c,e){return c.index-e.index});for(var g=[],a=0;a<d.length;a++)g.push(d[a].sc);return g}};return b}();c.od=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){var a=
function(){function b(){}b.prototype.mb=function(b,e){if(b){if(b.length<=e)return b;for(var d=1,a=Math.floor(Number.MAX_VALUE/4),g=b.length;d<a;){for(var p=b.length-1;0<=p;p--)if(c.Aa.Rb(b[p])<d&&(b.splice(p,1),g--),g<=e)return b;d*=4}return(new c.od).mb(b,e)}};return b}();c.Tg=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){var a=c.utils.hasOwnPropertyDefined,b=function(){function e(d,b,a){this.version=2;this.resourceTimingInfo={};this.ie={};this.je={};this.cf={};this.df={};this.uc=
[];this.hh=function(e,d,b){if(e&&d&&0<d.length){this.jk=e;for(var a=new k,h=new k,g=0;g<d.length;g++){var r=d[g],p=c.utils.parseURI(c.utils.N.Z(r.name)),u=r.initiatorType,C=f.Aa.be(p),l=new f.ld(r);this.uc.push({u:this.qk(p),i:a.Zd(this.je,u),r:h.Zd(this.df,C),f:l.Vd,o:this.ei(0===g&&r.isBase,l.Je,e,b),m:l.marks,e:c.utils.isDefined(r.encodedBodySize)?r.encodedBodySize:-1,d:c.utils.isDefined(r.decodedBodySize)?r.decodedBodySize:-1,s:c.utils.isDefined(r.transferSize)?r.transferSize:-1,p:c.utils.isDefined(r.nextHopProtocol)?
r.nextHopProtocol:""})}}};var g=e.fi();this.xh(g,d);d=this.Pj(g,d);this.hh(b||c.monitor.perfMonitor.navTiming&&c.monitor.perfMonitor.navTiming.navigationStart,d,a);this.clearResourceTimings()}e.Yb=function(){var d=c.conf.userConf&&c.conf.userConf.resTiming&&c.conf.userConf.resTiming.sampler;e.Oj=d&&"FirstN"==d?new f.fg:d&&"TopN"==d?new f.od:new f.Tg};e.prototype.ge=function(c,e){c[e]=c[e]?c[e]+1:1};e.prototype.qk=function(e){return c.utils.pk(e,"number"===typeof c.conf.userConf.maxResUrlSegmentLength?
c.conf.userConf.maxResUrlSegmentLength:c.conf.Yf,"number"===typeof c.conf.userConf.maxResUrlSegmentNumber?c.conf.userConf.maxResUrlSegmentNumber:c.conf.Zf,c.conf.Lg,c.conf.Kg)};e.prototype.xh=function(c,e){c&&this.he(c);if(e&&0<e.length)for(var b=0;b<e.length;b++)this.he(e[b])};e.prototype.he=function(e){var b=c.utils.parseURI(c.utils.N.Z(e.name)),b=f.Aa.be(b);this.ge(this.ie,e.initiatorType);this.ge(this.cf,b)};e.prototype.Pj=function(d,b){if(b&&0<b.length){var k=c.conf.userConf&&c.conf.userConf.resTiming&&
c.conf.userConf.resTiming.maxNum||c.conf.Gg;d&&k--;b=e.Oj.mb(b,k);d&&b.unshift(d)}return b};e.prototype.ei=function(e,b,k,f){return e?1:c.utils.isDefined(f)?Math.round(b+k-f):Math.round(b)};e.prototype.build=function(){return 0==this.uc.length?null:{v:this.version,ic:this.ie,it:this.je,rc:this.cf,rt:this.df,f:f.ld.ki(),t:this.jk,r:this.uc}};e.fi=function(){var e=c.monitor.perfMonitor.navTiming,b=null;if(e){var b={},k;for(k in e)a(e,k)&&(b[k]=e[k]);b.initiatorType="other";b.name=document.URL;b.navigationStart&&
!b.startTime&&(b.startTime=b.navigationStart);b.isBase=!0}return b};e.prototype.clearResourceTimings=function(){c.conf.userConf&&c.conf.userConf.resTiming&&c.conf.userConf.resTiming.clearResTimingOnBeaconSend&&c.monitor.perfMonitor.clearResourceTimings()};return e}();f.ResourceTimingInfoBuilder=b;var k=function(){function c(){this.kj=1}c.prototype.Zd=function(c,e){c[e]||(c[e]=this.kj++);return c[e]};return c}();b.Yb()})(c.events||(c.events={}))})(g||(g={}));(function(c){c.events||(c.events={})})(g||
(g={}));(function(c){(function(f){var a=function(){function b(){}b.prototype.A=function(b,e){void 0===e&&(e={});var d={eventGUID:b.guid(),eventType:b.type(),eventUrl:c.utils.N.Z(b.url()||document.URL),timestamp:c.utils.now()};b.type()!==c.EventType.PageView&&c.utils.mergeJSON(d,{parentGUID:b.parentGUID()||c.correlation.getPageGUID(),parentUrl:c.utils.N.Z(b.parentUrl()||document.URL),parentType:b.parentType()||(c.utils.compareWindows(top,window)?c.EventType.PageView:c.EventType.IFRAME)});var a=c.EventType[b.type()],
a=f.Q.ui(a,c.conf.userConf,e,c.conf.ya),g;for(g in a)d[g]=a[g];return d};return b}();f.va=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){var a=c.utils.isNumber,b=c.utils.isString,k=c.utils.isObject,e=c.utils.Jd,d=c.utils.$b,h=c.utils.isBoolean,g=function(){function d(){}d.fc=function(e,d){var b=!1;if(k(e)){var f=c.utils.fa(e);if(!f||f.length<=d)b=!0}return b};d.Dc=function(c,e,k){if(b(e))if(e.length>k)d.oa(c,k,e.length);else return e;else d.bc(c,"string")};d.ib=function(c,e){return function(b,
f,a){if(k(f)){var g,h;for(h in f)c(f[h])?(g=g||{},g[h]=f[h]):d.bc(b,e,h);if(g){if(d.fc(g,a))return g;d.oa(b,a)}}else d.bc(b,"object")}};d.bc=function(c,d,b){e(c+" dropped because it was not a "+d+(b?", field name "+b:""))};d.oa=function(c,d,b){e("User event info field "+c+" dropped because it is too long"+(b?" ("+b+" exceeds "+d+")":""))};return d}();g.ui=function(e,d,b,f){if(d=d&&d.userEventInfo&&d.userEventInfo[e]){try{var a=c.utils.isFunction(d)?d.call(null,b):d}catch(h){c.exception(h,"M134",e)}if(k(a))return g.vk(a,
f)}};g.vk=function(c,e){var d={},b;for(b in g.Td)if(b in c){var k=g.Td[b](b,c[b],e);k&&(d[b]=k)}return d};g.tj=g.ib(b,"string");g.sj=g.ib(d,"integer");g.Fe=g.ib(a,"number");g.rj=g.ib(h,"boolean");g.Td={userPageName:g.Dc,userData:g.tj,userDataLong:g.sj,userDataDouble:g.Fe,userDataBoolean:g.rj,userDataDate:g.Fe};f.Q=g})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){var a=c.utils.isDefined,b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}v(e,b);e.setPageName=
function(c){e.$=c};e.addUserData=function(c,b){e.Oa=e.Oa||{};e.Oa[c]=b};e.prototype.A=function(d){d=b.prototype.A.call(this,d||new f.PageView);var g=this.mi(),r=this.gi();c.conf.viz&&(g&&c.utils.Nb(document.getElementById(c.conf.viz),g,"navtime"),c.utils.Nb(document.getElementById(c.conf.viz),r,"cookie"));r.PLC=1;g&&(g.PLC=1);c.monitor.ErrorMonitor.hadErrors&&(r.EPM=1,g&&(g.EPM=1));c.utils.mergeJSON(d,{eventGUID:c.correlation.getPageGUID(),eventType:c.utils.compareWindows(top,window)?c.EventType.PageView:
c.EventType.IFRAME,cookieMetrics:r});var p=-1;g&&g.timestamp?p=g.timestamp:r&&r.timestamp&&(p=r.timestamp);0<p&&c.utils.mergeJSON(d,{timestamp:p});g&&(d.metrics=g);document.referrer&&null!==document.referrer&&0<document.referrer.length&&(d.pageReferrer=c.utils.N.Z(document.referrer));g=e.ni();0<g.length&&(d.pageTitle=g);g=c.correlation.ce();null!==g&&(d.serverMetadata=g);c.conf.spa2?0<c.monitor.qa.basePageResourceBuffer.length?(g=(new f.ResourceTimingInfoBuilder(c.monitor.qa.basePageResourceBuffer)).build(),
c.monitor.qa.basePageResourceBuffer=[]):g=null:g=c.monitor.perfMonitor.resTiming?(new f.ResourceTimingInfoBuilder(c.monitor.perfMonitor.resTiming)).build():null;null!==g&&(d.resourceTimingInfo=g);!a(d.userData)&&a(e.Oa)&&(f.Q.fc(e.Oa,c.conf.ya)?d.userData=e.Oa:f.Q.oa("userData",c.conf.ya));!a(d.userPageName)&&a(e.$)&&(f.Q.Dc("userPageName",e.$,c.conf.za)?d.userPageName=e.$:f.Q.oa("userPageName",c.conf.za));e.userPageName=d.userPageName;return d};e.prototype.mi=function(){if(!c.monitor.perfMonitor.navTiming)return null;
var d={},b=e.ae(c.monitor.perfMonitor.navTiming,d,"NT"),k=f.metricSpec[c.EventType.PageView],a;for(a in k){var g=k[a];b.add(g.name,g.start,g.end)}d.timestamp=c.monitor.perfMonitor.navTiming.navigationStart;return d};e.prototype.gi=function(){var d={};c.commands.marks&&(e.ae(c.commands.marks,d,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte","onready").add("PRT","onready","onload").add("DOM","starttime","onready"),d.timestamp=
c.commands.marks.starttime?c.commands.marks.starttime:c.commands.marks.firstbyte);return d};e.ni=function(){var e=c.conf.userConf,e=e&&e.page,b;b=e&&"captureTitle"in e?e.captureTitle:!0;var k,f;e&&(k="title"in e,f=e.title);k=b?k?c.utils.isFunction(f)?f():f:document.title:"";if(c.utils.isString(k))return k;c.utils.Jd("Ignoring wrong type of page title: "+typeof k);return""};e.gh=function(e,b,k,f,a,g){b=f[b];k=f[k];b&&k?a[e]=k-b:c.log("M135",g,e,b,k)};e.ae=function(c,b,k){var f={add:function(a,g,s){e.gh(a,
g,s,c,b,k);return f}};return f};return e}(f.va);f.W=b})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){(function(f){function b(d,f){var a,p=f[d],t=typeof p;n.push(d);var l=q[n.join(".")];if(c.utils.isFunction(l))a=l(p);else switch(t){case "string":a="number"==typeof l?m(p,e,l):e(p);break;case "number":a=r(p);break;case "object":if(p)if(c.utils.isArray(p))a=g(p,!1,!1);else{a=[];for(var y in p)s(p,y)&&(t=b(y,p))&&(k(d)&&"timestamp"==y||a.push({gb:y,v:t}));if(k(d)){for(p=0;p<a.length;p++)a[p]=
a[p].gb+e(":")+a[p].v;a=e("{")+a.join(e(","))+e("}")}else{for(p=0;p<a.length;p++)y=a[p],t=y.gb,c.conf.Bf||((l=c.conf.we[y.gb])?t=l:c.error("M136",y.gb)),a[p]=t+"="+y.v;a=a.join("&")}}else a=null}n.pop();return a}function k(c){return"navOrXhrMetrics"==c||"cookieMetrics"==c}function e(c){return"undefined"===typeof c||null===c||0===c.length?null:encodeURIComponent(c)}function d(c){return encodeURIComponent(encodeURIComponent(c))}function g(c,d,f){void 0===d&&(d=!1);void 0===f&&(f=!0);if(0===c.length)return null;
var k=[];if(d)k=c;else for(d=0;d<c.length;d++)k.push(b(d,c));return e("[")+k.join(e(","))+e(f?">":"]")}function r(c){c=Math.round(c);c<f.hd&&(c=f.hd);c>f.ed&&(c=f.ed);return e(c)}function p(c,b){if(c>b||0>c)c=f.Qg;return e(c)}function m(e,b,d,f){void 0===f&&(f=!0);if("undefined"===typeof e||null===e||0===e.length)return null;var k=3<=d?"...":"";c.assert(d>=k.length);for(var a=!1,g=null;;){try{g=b(e);if(null===g)return null;if(g.length<=d)break}catch(h){}var r;a?r=e.length-1:(a=!0,r=d-=k.length);var p=
f?0:Math.max(e.length-r,0);e=e.substr(p,r)}a&&(g=f?g+k:k+g);return g}function t(e,b,d){if(0==d)return f.wb;if(b<e)return 0;b=f.wb+(b-e)/d;c.assert(b>=f.wb);c.log("M137",e,b);return b}var s=c.utils.hasOwnPropertyDefined;f.Qg=-1;f.xa=180;f.Ig=50;f.Jg=50;f.Cg=40;f.wb=50;f.rg=50;f.gd=128;f.xg=30;f.yg=30;f.wg=30;f.Eg=8;f.hd=-99999;f.ed=999999;f.sg=2E3;f.Hg=2;f.tg=99999999;var q={".pageUrl":f.xa,".parentPageUrl":f.xa,".pageReferrer":f.xa,".pageTitle":f.Ig,".userPageName":f.Jg,".geoCountry":f.xg,".geoRegion":f.yg,
".geoCity":f.wg,".localIP":f.Eg,".otherClientRequestGUIDs":function(c){c=c||[];var e=c.slice(0,f.Hg);return g(e,!1,e.length<c.length)},".btTime":function(e){e=e||[];for(var b=e.slice(0,c.conf.ug),d=[],k=0;k<b.length;k++){var m=b[k];d.push(g([p(Number(m[0]),f.tg),r(m[1]),r(m[2])],!0,!1))}return g(d,!0,b.length<e.length)},".ajaxError":function(c){return g([d(c[0]),m(c[1],d,f.rg)],!0,!1)},".userData":function(c){c=c||[];for(var e=!1,b=0,k=[],r=0;r<c.length;r++){var p=c[r];k[r]=g([d(p[0]),d(p[1])],!0,
!1);b+=k[r].length;if(b>f.gd){e=!0;break}}for(;;){c=g(k,!0,e);if(null===c||c.length<=f.gd)return c;k.pop();e=!0}}},n=[];f.Qh=function(e,k){void 0===k&&(k=!0);n=[];var p=[];e.errors&&(p=e.errors,e.errors=null);var q=b("",{"":e});if(p&&0<p.length){for(var s=t(k?870:354,f.sg-q.length,p.length),l=[],y=0;y<p.length;y++){var v=p[y],z=c.utils.N.Sd(c.utils.N.Z(v[0]));l.push(g([m(z,d,f.Cg,!1),c.utils.$b(v[1])?r(v[1]):-1,m(v[2],d,s)],!0,!1))}p=g(l,!0,!1);q+="&errors="+p}return q};f.el=b;f.Fl=e;f.element=d;
f.Zk=g;f.al=r;f.tl=p;f.truncate=m;f.Al=t})(f.bd||(f.bd={}))})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(f){var a=c.utils.hasOwnPropertyDefined,b=c.utils.Wa,k=function(){function e(){}e.prototype.hb=function(b,k,a){for(var g=[],m=[],t=null,s=[],q=0;q<b.length;q++){var n=b[q];if(n.eventType===c.EventType.Error){var v=n;m.push([n.eventUrl+"",c.utils.$b(v.line)?v.line:void 0,v.message+""])}else{if(n.eventType===c.EventType.PageView||n.eventType===c.EventType.IFRAME)t=n;s.push(n)}}b=
s;if(0<m.length)for(t&&(t.errors=m.splice(0,c.conf.Ag));0<m.length;)n=m.splice(0,c.conf.zg),t=e.wj.A(),t.errors=n,t.isErrorEvent=!0,t.cookieMetrics=null,t.metrics=null,t.resourceTimingInfo=null,b.push(t);for(m=0;m<b.length;m++)n=b[m],c.log("M138"),n.resourceTimingInfo=null,e.bi(n,k,a),t=e.transform(n),g.push(f.bd.Qh(t,n.isErrorEvent));return g};e.bi=function(e,b,f){e.ver=this.lg;e.rootGUID=f.Tb();e.geo=b;e.dataType="R";e.eom=1;e.eumAppKey=c.conf.appKey;e.PLC=1};e.transform=function(c){var b={};e.Gf("",
{"":c},b);return b};e.Gf=function(d,f,k){f=f[d];var g=e.se[d];if("metrics"===d||"cookieMetrics"===d)k[g]=f;else if("btTime"===d&&c.utils.isArray(f)&&0<f.length){d=[];for(var m=0;m<f.length;m++)d.push([f[m].id,f[m].duration,f[m].ert]);k[g]=d}else if("userData"===d&&c.utils.isObject(f))k[g]=c.utils.fj(f);else if(!(d&&-1<b(["userDataLong","userDataDouble","userDataBoolean","userDataDate"],d)))if(c.utils.isObject(f))for(m in f)a(f,m)&&e.Gf(m,f,k);else e.se[d]&&("eventType"===d&&f>c.EventType.Ajax&&(f=
c.utils.compareWindows(top,window)?c.EventType.PageView:c.EventType.IFRAME),k[g]=f)};return e}();k.wj=new c.events.W;k.lg=3;k.se={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",metrics:"navOrXhrMetrics",xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",
cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",dataType:"dataType",country:"geoCountry",region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};f.pg=k})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(c){var a=function(){function c(){}c.prototype.send=
function(){};return c}();c.dg=a})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(c){var a=function(){function c(){}c.prototype.hb=function(){return null};return c}();c.cg=a})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(c){this.cj=c}b.prototype.send=function(b){try{this.cj.postMessage(c.utils.fa(b)),c.log("M139"),f.numBeaconsSent+=1}catch(e){c.log("M140")}};return b}();f.ig=a})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){(function(f){var a=
function(){function b(){}b.prototype.hb=function(b,e,d){b={ver:c.conf.agentVer,dataType:"R",rootGUID:d.Tb(),events:b};c.channel.M.K&&c.channel.M.K.id&&(b.agentId=c.channel.M.K.id);e&&(b.geo=e);return b};return b}();f.hg=a})(c.beacons||(c.beacons={}))})(g||(g={}));(function(c){var f=function(){function f(){}f.Id=function(b,f){if(!b)return null;var e=b.ADRUM.lifecycle;if(!e||!e.getPhaseCallbackTime)return null;var d=f.getPhaseCallbackTime("AT_ONLOAD"),e=e.getPhaseCallbackTime("AT_ONLOAD"),a=null==e;
return null==d?(c.error("M141"),null):c.lifecycle.getPhaseID(a||d<=e?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};return f}();c.Sg=f;c.cPLPI=f.Id})(g||(g={}));(function(c){(function(f){var a=function(){function b(b){this.ready=!1;this.geoResolverUrl=b;c.utils.isString(b)&&0<c.utils.trim(b).length&&(this.geoResolverUrl=b+"/resolve.js")}b.prototype.init=function(b){this.channel=b;if(this.Jb()&&(c.geo=this.Hc(),this.nh()||this.jb()&&!this.Xd())){this.channel.wc(c.geo.result);return}this.Xd()?(this.jb()&&(this.geoResolverUrl+=
"?ip="+encodeURIComponent(c.conf.userConf.geo.localIP)),this.tk()):(this.ready=!0,this.channel.onResolverReady())};b.prototype.Jb=function(){return c.utils.isDefined(c.conf.userConf)&&c.utils.isDefined(c.conf.userConf.geo)};b.prototype.jb=function(){return this.Jb()&&c.utils.isDefined(c.conf.userConf.geo.localIP)&&!c.utils.isDefined(c.conf.userConf.geo.city)&&!c.utils.isDefined(c.conf.userConf.geo.region)&&!c.utils.isDefined(c.conf.userConf.geo.country)};b.prototype.Hc=function(){return{failed:!1,
result:{country:c.conf.userConf.geo.country,region:c.conf.userConf.geo.region,city:c.conf.userConf.geo.city,localIP:this.Sh(c.conf.userConf.geo.localIP)}}};b.prototype.nh=function(){return this.Jb()&&c.utils.isDefined(c.conf.userConf.geo.localIP)&&c.utils.isDefined(c.conf.userConf.geo.city)&&c.utils.isDefined(c.conf.userConf.geo.region)&&c.utils.isDefined(c.conf.userConf.geo.country)};b.prototype.Xd=function(){return c.utils.isString(this.geoResolverUrl)&&0<c.utils.trim(this.geoResolverUrl).length};
b.prototype.Sh=function(c){if(null==c||0==c.length)return null;c=c.split(".");if(4!=c.length)return null;for(var e=[],b=0;b<c.length;b++){var f=parseInt(c[b]);if(isNaN(f)||0>f||255<f)return null;e.push(("0"+f.toString(16)).slice(-2))}return e.join("")};b.prototype.tk=function(){c.geo={failed:!1,result:null};c.utils.loadScriptAsync(this.geoResolverUrl);var f=this;c.utils.tryPeriodically(b.Db,function(){return f.isReady()},function(){f.onReady()},function(){f.gc()})};b.prototype.isReady=function(){this.ready||
(this.ready=c.geo&&(c.geo.failed||null!==c.geo.result))||c.log("M142");return this.ready};b.prototype.onReady=function(){c.geo.failed?(c.log("M143"),this.jb()&&(c.geo=this.Hc())):(c.assert("object"===typeof c.geo.result),c.log("M144",c.geo.result));c.geo&&c.geo.result&&this.channel.wc(c.geo.result);this.channel.onResolverReady()};b.prototype.gc=function(){c.log("M145");this.jb()&&(c.geo=this.Hc());c.geo&&c.geo.result&&this.channel.wc(c.geo.result);this.ready=!0;this.channel.onResolverReady()};b.Db=
function(c){return 10<c?-1:[1,50,100,500][c-1]||1E3};return b}();f.gg=a})(c.channel||(c.channel={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(){this.ready=!1;this.channel=null}b.prototype.init=function(f){this.channel=f;b.O=b.O||b.di();this.ready=!b.O.cb;var e=this;if(b.O.cb)c.log("M146"),b.O.cb.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){c.log("M147");e.ready=!0;e.onReady()});else e.onReady()};b.prototype.isReady=function(){this.isReady||c.log("M148");
return this.ready};b.prototype.onReady=function(){this.channel.Uj(b.O);this.channel.onResolverReady()};b.di=function(){for(var f=window,e,d=b.pe(f),a=window;a.parent&&!c.utils.compareWindows(a,a.parent);){a=a.parent;d=d||b.pe(a);try{a.ADRUM&&(e=e||a,f=a)}catch(g){}}return new c.Rf(e,f,d)};b.pe=function(c){try{return 0==c.document.URL.indexOf("https:")}catch(e){}};return b}();a.O=null;f.Sf=a})(c.channel||(c.channel={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(e,d,k){this.events=
[];this.ba={};this.Za=NaN;this.Y=[];this.Qb=!1;this.bufferMode=c.conf.userConf&&c.conf.userConf.channel&&"undefined"!==typeof c.conf.userConf.channel.bufferMode?c.conf.userConf.channel.bufferMode:!0;this.nb=-1;this.kk=e;this.sh=d;this.Y.push(new f.gg(k));this.Y.push(new f.Sf);this.Y.push(new f.M)}b.create=function(){var e,d;e=b.Bj();c.utils.isDefined(e)?(e=new c.beacons.ig(e),d=new c.beacons.hg):b.Ji()&&!c.conf.sendImageBeacon?(e=new c.beacons.Uf,d=new c.beacons.Tf):b.Pi()?(e=new c.beacons.dg,d=new c.beacons.cg):
(e=new c.beacons.qg,d=new c.beacons.pg);e=new b(e,d,c.conf.geoResolverUrl);e.init();return e};b.prototype.init=function(){for(var c=0;c<this.Y.length;c++)this.Y[c].init(this)};b.prototype.yk=function(b){return(b.parentType===c.EventType.VPageView||b.parentType===c.EventType.NG_VIRTUAL_PAGE)&&null!==this.ba[b.parentGUID]};b.prototype.oc=function(b){var d=b.parentGUID;if(!c.utils.isDefined(this.ba[d])){this.ba[d]=[];var f=this,k=b.eventGUID;c.utils.oSTO(function(){f.Mb(k)},1E4)}this.ba[d].push(b)};
b.prototype.report=function(e){e.sequenceId=c.lf.Gd.ji();e.timestamp=e.timestamp||c.utils.now();this.yk(e)?this.oc(e):this.events.push(e);1==this.events.length&&(this.Za=c.utils.now());var d=e.parentGUID;d&&d!==c.correlation.getPageGUID()||this.Mb(e.eventGUID);b.Ni(e)&&(this.Qb=!0);this.Gc()};b.prototype.Mb=function(c){var b=this.ba[c];this.ba[c]=null;if(b&&0!=b.length)for(this.events=this.events.concat(b),c=0;c<b.length;c++)this.Mb(b[c].eventGUID)};b.prototype.Ri=function(b){return b.eventType===
c.EventType.PageView||b.eventType===c.EventType.IFRAME};b.prototype.th=function(){for(var b=0;b<this.events.length;b++){var d=this.events[b];if(this.Ri(d)){var f=this.O.cb;f&&(d.parentLifecyclePhase=c.Sg.Id(f,c.lifecycle),d.parentGUID=f.ADRUM.correlation.getPageGUID(),d.parentUrl=c.utils.N.Z(f.document.URL),c.utils.isDefined(f.ADRUM.events.W.userPageName)&&(d.xj=f.ADRUM.events.W.userPageName),d.parentType=c.utils.compareWindows(top,f)?c.EventType.PageView:c.EventType.IFRAME)}}};b.prototype.Rj=function(){if(0==
this.events.length)c.log("M149");else{this.th();var b=this.Ic(this.events,this.O),d=this.sh.hb(this.events,this.ci,this.O);this.kk.send(d,b);this.events=[];this.Za=Number.POSITIVE_INFINITY}};b.prototype.onResolverReady=function(){this.Gc()};b.prototype.wc=function(c){this.ci=c};b.prototype.Uj=function(c){this.O=c};b.prototype.addResolver=function(c){c.init(this);this.Y.push(c)};b.prototype.Kj=function(){for(var c=0;c<this.Y.length;c++)if(!this.Y[c].isReady())return!1;return!0};b.prototype.re=function(){return this.Za+
c.conf.dd>c.utils.now()};b.prototype.Wi=function(){return this.events.length<c.conf.vg};b.prototype.Ic=function(b,d){if(d.Ic||c.conf.userConf.useHTTPSAlways)return!0;for(var f=0;f<b.length;f++){var k=b[f];if(k.eventUrl&&0==k.eventUrl.indexOf("https:"))return!0}return!1};b.prototype.getEventsWithParentGUID=function(c){return this.ba[c]||[]};b.prototype.Gc=function(){if(this.Kj())if(this.xk()){if(this.re()&&0<this.events.length&&0>this.nb){var b=this;this.nb=c.utils.oSTO(function(){b.Gc()},c.conf.dd+
this.Za-c.utils.now())}}else clearTimeout(this.nb),this.nb=-1,this.Qb=!1,this.Rj()};b.Ni=function(b){return b.eventType===c.EventType.PageView||b.eventType===c.EventType.IFRAME||b.eventType===c.EventType.VPageView};b.prototype.xk=function(){return this.bufferMode&&!this.Qb&&this.Wi()&&this.re()};b.Ji=function(){var c="undefined"!==typeof JSON&&!(!JSON||!JSON.stringify);return window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&c};b.Cj=function(){if(c.utils.isDefined(window.webkit)&&c.utils.isDefined(window.webkit.messageHandlers)&&
c.utils.isDefined(window.webkit.messageHandlers.ADEUM_js_handler)&&c.utils.isFunction(window.webkit.messageHandlers.ADEUM_js_handler.postMessage))return window.webkit.messageHandlers.ADEUM_js_handler};b.Aj=function(){if(c.utils.isDefined(window.ADEUM_js_handler)&&c.utils.isFunction(window.ADEUM_js_handler.postMessage))return window.ADEUM_js_handler};b.Bj=function(){return b.Aj()||b.Cj()};b.Pi=function(){return c.conf.userConf&&c.conf.userConf.beacon&&c.conf.userConf.beacon.neverSendImageBeacon};return b}();
f.Channel=a;var b=a.create();f.report=function(c){b.report(c)};f.addResolver=function(c){b.addResolver(c)};f.getEventsWithParentGUID=function(c){return b.getEventsWithParentGUID(c)}})(c.channel||(c.channel={}))})(g||(g={}));(function(c){var f=function(){function f(){}f.Pe=function(){return window.attachEvent?c.utils.isFunction(window.addEventListener)?this.Jc:this.uf:this.Af};f.Oe=function(b){var k=null;switch(f.Pe()){case f.Af:k=b.parentPhase();break;case f.Jc:k=c.lifecycle.findPhaseAtNominalTime(b.getSendTime());
break;case f.uf:k=null}return c.lifecycle.getPhaseID(k)};return f}();f.Af="uCT";f.Jc="uNET";f.uf="tIA";c.Ta=f})(g||(g={}));(function(c){(function(f){var a=c.utils.hasOwnPropertyDefined,b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}v(e,b);e.prototype.A=function(d){var a=b.prototype.A.call(this,d,e.getContext(d)),g=d.url(),p=d.getSendTime(),m=d.getFirstByteTime(),t=d.getRespAvailTime(),s=d.getRespProcTime(),q=d.parentPhase();c.assert(null!==g&&null!==p&&null!==m&&null!==
t&&null!==s,"M150",g,p,m,t,s,q);if(null===g||null===p||null===m||null===t||null===s)return null;g=d.error();p={PLC:1,FBT:m-p,DDT:t-m,DPT:s-t,PLT:s-p,ARE:g?1:0};m=d.url();if(!e.bj(p,m))return null;c.conf.viz&&c.utils.Nb(document.getElementById(c.conf.viz),p,"xhr");c.utils.mergeJSON(a,{eventUrl:c.utils.N.Z(m),parentType:d.parentType()||c.EventType.PageView,parentLifecyclePhase:d.parentPhaseId(),metrics:p,method:d.method(),timestamp:d.timestamp(),ajaxError:g&&[g.status,g.msg||""],xhrStatus:d.xhrStatus()});
(d=d.parameter())&&f.Q.fc(d,c.conf.ya)?a.parameter=d:d&&f.Q.oa("parameter",c.conf.ya);a.parentType==c.EventType.VPageView&&c.conf.spa2?c.utils.mf(a,f.Qa.userPageName):c.utils.mf(a,f.W.userPageName);return a};e.getContext=function(c){return{url:c.url()||"",method:c.method()||""}};e.bj=function(b,e){for(var f in b)if(a(b,f)){var k=b[f];if(0>k)return c.error("M151",f,k,e),!1}return!0};return e}(f.va);f.qd=b})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){var a=function(b){function f(){return null!==
b&&b.apply(this,arguments)||this}v(f,b);f.prototype.A=function(e){var f=b.prototype.A.call(this,e);f&&(e=e.allResponseHeaders()||"",(e=c.correlation.ti(e))&&null!==e&&null!==e.clientRequestGUID&&(f.eventGUID=e.clientRequestGUID),null!==e&&(f.serverMetadata=e));return f};return f}(f.qd);f.Lf=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){var a=function(b){function k(){return null!==b&&b.apply(this,arguments)||this}v(k,b);k.prototype.A=function(e){var d=b.prototype.A.call(this,
e);c.utils.mergeJSON(d,{message:e.msg()||"",timestamp:e.timestamp(),line:e.line(),stack:e.stack(),parentPageName:d.parentType==c.EventType.VPageView&&c.conf.spa2?f.Qa.userPageName:f.W.userPageName});c.utils.isString(d.userPageName)||(d.userPageName=d.xj);return d};return k}(f.va);f.Rg=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){(function(a){a.build=function(b){var k={},e=c.metricSpec[b.type()],d;for(d in e){var a=e[d];if(null!==a.name&&b.perf.getEntryByName(a.start)&&b.perf.getEntryByName(a.end)){b.perf.measure(a.name,
a.start,a.end);var g=b.perf.getEntryByName(a.name);k[a.name]=g&&0<=g.duration&&g.duration||null}}for(d in k)k[d]=Math.round(k[d]);return k}})(c.xb||(c.xb={}))})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){var a=function(b){function a(){return null!==b&&b.apply(this,arguments)||this}v(a,b);a.prototype.A=function(e){var d=b.prototype.A.call(this,e),a=c.xb.build(e);a.PLC=1;d.metrics=a;d.timestamp=e.timestamp();e=(new c.ResourceTimingInfoBuilder(e.resTiming())).build();null!==e&&(d.resourceTimingInfo=
e);return d};return a}(c.va);c.pd=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(f){var a=function(b){function a(){return null!==b&&b.apply(this,arguments)||this}v(a,b);a.setPageName=function(c){a.$=c};a.prototype.A=function(e){var d=b.prototype.A.call(this,e),g=f.xb.build(e);g.PLT=e.timestamp()-e.startTime;g.PLC=1;d.metrics=g;d.timestamp=e.timestamp();e=(new f.ResourceTimingInfoBuilder(e.resTiming(),null,e.startTime)).build();null!==e&&(d.resourceTimingInfo=e);!c.utils.isDefined(d.userPageName)&&
c.utils.isDefined(a.$)&&(f.Q.Dc("userPageName",a.$,c.conf.za)?d.userPageName=a.$:f.Q.oa("userPageName",c.conf.za),a.$=void 0);a.userPageName=d.userPageName;return d};return a}(f.va);f.Qa=a})(c.events||(c.events={}))})(g||(g={}));(function(c){(function(c){var a=function(c){function f(){return null!==c&&c.apply(this,arguments)||this}v(f,c);f.prototype.A=function(e){var f=c.prototype.A.call(this,e);f&&(f.metrics.VDC=e.digestCount()||0);return f};return f}(c.pd);c.Pg=a})(c.events||(c.events={}))})(g||
(g={}));(function(c){var f=c.events||(c.events={});f.Ye={};c=[{ga:f.PageView,ea:new f.W},{ga:f.Ajax,ea:new f.qd},{ga:f.AdrumAjax,ea:new f.Lf},{ga:f.Error,ea:new f.Rg},{ga:f.VPageView,ea:new f.pd},{ga:f.ia,ea:new f.Qa},{ga:c.ng.NgVPageView,ea:new f.Pg}];for(var a=0;a<c.length;a++){var b=c[a];b.ga.prototype._regId=a;f.Ye[a]=b.ea}})(g||(g={}));(function(c){(function(f){f.reportEvent=function(f){var b=c.events.Ye[f._regId];b?(b=b.A(f),c.utils.isDefined(b)&&(c.log("M153",c.EventType[f.type()]),c.channel.report(b))):
c.log("M152",c.EventType[c.eventType])}})(c.reporter||(c.reporter={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(){this.ready=!1}b.prototype.onReady=function(){this.ready=!0;this.channel.onResolverReady()};b.prototype.isReady=function(){this.ready||c.log("M154");return this.ready};b.prototype.init=function(c){this.channel=c};return b}();f.dh=a})(c.commands||(c.commands={}))})(g||(g={}));(function(c){(function(f){var a=new f.dh;c.channel.addResolver(a);f.marks={};f.mark=function(b,
a){c.log("M155",b,a);f.marks[b]=a};f.reportOnload=function(b){c.utils.oSTO(function(){c.log("M156");c.reporter.reportEvent(b);a.onReady()},c.conf.ah)};f.reportEvent=function(){c.reporter.reportEvent.apply(c.reporter,arguments)};f.addResolver=function(b){c.channel.addResolver(b)};f.reportXhr=function(b){c.log("M157");c.Ta.Pe()==c.Ta.Jc?(c.log("M158"),c.utils.oSTO(function(){b.parentPhaseId(c.Ta.Oe(b));c.reporter.reportEvent(b)},0)):(b.parentPhaseId(c.Ta.Oe(b)),c.reporter.reportEvent(b))};f.listenForOkToSendChildFrameBeacons=
function(b){c.log("M159");try{b()}catch(f){c.exception(f,"M160")}};f.reportPageError=function(b){var f=b.url();c.log("M161",b.msg(),f,b.line(),b.stack());f&&0!==f.length||b.url("CROSSORIGIN");c.reporter.reportEvent(b)};f.setPageName=function(b){c.utils.isString(b)&&0<c.utils.trim(b).length&&c.events.W.setPageName(b)};f.setVirtualPageName=function(b){c.utils.isString(b)&&0<c.utils.trim(b).length&&c.conf.spa2&&c.events.Qa.setPageName(b)};f.addUserData=function(b,f){c.events.W.addUserData(b,f)};f.call=
function(c){c()}})(c.commands||(c.commands={}))})(g||(g={}));(function(c){(function(c){c.Rd=function(a){return encodeURIComponent(c.N.qj(a))}})(c.utils||(c.utils={}))})(g||(g={}));(function(c){(function(f){var a=function(){function b(){}b.prototype.setUp=function(){this.hj();c.utils.addEventListener(window,"pagehide",b.Pc);c.utils.addEventListener(window,"beforeunload",b.Pc);c.utils.addEventListener(window,"unload",b.Pc)};b.prototype.hj=function(){(this.startTime=b.$h()||b.Zh())&&c.commands.mark("starttime",
this.startTime)};b.$h=function(){var b;try{if(c.utils.isDefined(window.external)&&c.utils.isNumber(window.external.pageT))b=(new Date).getTime()-window.external.pageT;else if(c.utils.isDefined(window.gtbExternal)&&c.utils.isFunction(window.gtbExternal.pageT)){var e=window.gtbExternal.pageT();c.utils.isNumber(e)&&(b=(new Date).getTime()-e)}else c.utils.isDefined(window.chrome)&&c.utils.isFunction(window.chrome.csi)&&(e=window.chrome.csi(),c.utils.isDefined(e)&&c.utils.isNumber(e.pageT)&&(b=(new Date).getTime()-
e.pageT));b&&(b=Math.round(b),c.log("M162",b))}catch(f){c.exception(f,"M163")}return b};b.Zh=function(){var b=c.correlation.startTimeCookie;if(b){c.log("M164",b.startTime,b.startPage);var e=c.utils.Rd(document.referrer);if(e===b.startPage)if(isNaN(b.startTime))c.log("M165",b.startTime);else return b.startTime;else c.log("M166",e,b.startPage)}else c.log("M167")};b.Nh=function(b,e){var f=document.domain,a="https:"===document.location.protocol,g="ADRUM=s="+Number(new Date)+"&r="+c.utils.Rd(document.location.href),
p=g+";path=/";a&&(p+=";secure");c.log("M168",g);if(!c.conf.useStrictDomainCookies){for(var a=b(),f=f.split("."),m="",t=f.length-1;0<=t;t--){m="."+f[t]+m;c.log("M169",m);e(p+";domain="+m);var s=b();if(s!=a&&0<=s.indexOf(g)){c.log("M170");c.log("M171");return}}c.log("M172")}c.log("M173");e(p);c.log("M174")};return b}();a.Pc=function(){var c=!1;return function(){c||(c=!0,a.Nh(function(){return document.cookie},function(c){document.cookie=c}))}}();f.Pk=a;f.dk=new a})(c.monitor||(c.monitor={}))})(g||(g=
{}));(function(c){c.log("M175");c.monitor.dk.setUp();c.q.processQ();c.initEXTDone=!0;c.log("M176")})(g||(g={}))}};})();
